services:
  redis:
    image: redis:alpine
    container_name: "redis"
    working_dir: /redis
    networks:
      - mynet
    # ports:
    #   - "127.0.0.1:4721:4721"
    command: redis-server ./redis.conf
    volumes:
      - $PWD/redis:/redis
    restart: always

  web:
    build: 
      context: ./app
      args:
        - mode=prod
    depends_on:
      - redis
    links:
      - redis
    networks:
      - mynet
    ports:
      - "8000:8000"
    restart: always


networks:
  mynet:
    driver: bridge

