services:
  redis:
    image: redis:alpine
    container_name: "redis"
    working_dir: /redis
    networks:
      - mynet
    ports:
      - "4721:4721"
    command: redis-server ./redis.conf
    volumes:
      - ./redis/redis-data:/redis/
      - ./redis/redis.conf:/redis/redis.conf
      - ./redis/.log:/redis/.log

  web:
    build: ./app
    depends_on:
      - redis
    networks:
      - mynet
    ports:
      - "8000:5000"
    restart: always


networks:
  mynet:
    driver: bridge

